sudo: required
services:
  - docker

before_install:
  - docker build -t vectorkat/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run vectorkat/react-test npm test -- --coverage

after_success:
  - docker build -t vectorkat/multi-client ./client
  - docker build -t vectorkat/multi-nginx ./nginx
  - docker build -t vectorkat/multi-server ./server
  - docker build -t vectorkat/multi-worker ./worker
  
  # Login into docker CLI
  - echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_ID" --password-stdin

  # Take images and push to DockerHub
  - docker push vectorkat/multi-client
  - docker push vectorkat/multi-nginx
  - docker push vectorkat/multi-server
  - docker push vectorkat/multi-worker